### PR TITLE
fix/alias func bypass

### PR DESCRIPTION
**Pull request by EduardZaydler**

### CODE REVIEW

**Comment by clavinjune** [comment]
let me merge this one and try to push to npm again

**Comment by EduardZaydler** [comment]
@clavinjune ok, appriciate

**Comment by EduardZaydler** [comment]
@clavinjune, hello, could you push it today, please? really need it

**Comment by clavinjune** [comment]
pushed `0.0.1-dev.108240001`

**Comment by EduardZaydler** [comment]
@clavinjune hello, its me again, seems like i`ve made a mistake. there are no changes in the latest version from the last [commit](https://github.com/clavinjune/prometheus-codemirror-metricsql/pull/2/files)
image
and git submodule appeared appeared for an unknown reason, could you help, please?

**Comment by EduardZaydler** [comment]
@clavinjune, hello, could you help?

**Pull request merged**
