### PR TITLE
alias func

### PR DESCRIPTION
**Pull request by EduardZaydler**
This PR adds alias [VM](https://github.com/clavinjune/prometheus-codemirror-metricsql/pull/1) function to the metrcsql codemirror mode
image

### CODE REVIEW

**Comment by EduardZaydler** [comment]
@clavinjune, hello! Could you take a look at this, please?

**Comment by EduardZaydler** [comment]
hmm, why so many failed...

**Comment by EduardZaydler** [comment]
can i fix it somehow?

**Comment by EduardZaydler** [comment]
@clavinjune, also would appreciate if you push new version to npm registry, or i can try to do it myself (possibly will need help)

**Comment by clavinjune** [comment]
sure, I'll do this tomorrow @EduardZaydler

**Comment by clavinjune** [comment]
pushed to npm @EduardZaydler with version `0.0.1-dev.3007240001` https://www.npmjs.com/package/@clavinjune/codemirror-metricsql

**Comment by EduardZaydler** [comment]
@clavinjune sorry for disturbing, but run into an error in parser.js when trying to call func
image
image

but locally when was adding this in your repo everything was fine
probably i should've add it to isFunctionBypassed list, am i right?

added fixing [pr](https://github.com/clavinjune/prometheus-codemirror-metricsql/pull/2/files)

**Pull request merged**
